# name: Publish
# run-name: Publishing ${{ github.repository }} to AWS S3
# on:
#   release:
#     types: [published]
# jobs:
#   main-branch-check:
#     if: ${{ github.ref == 'refs/heads/main' }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "🍏 This job's status is ${{ job.status }}."

name: Publish
run-name: Publishing ${{ github.repository }} to AWS S3
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build-scripts
    steps:
      - uses: actions/checkout@v4
      - name: Check secret env
        run: ./hello-secret.sh
        shell: bash
        env:
          SECRET_ENV: ${{ secrets.TEST }}

